services:
  - type: web
    name: zep
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ZEP_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ZEP_NLP_SERVER_URL
        value: http://nlp:8080
